# Generated by Django 5.2.8 on 2025-11-12 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredBoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_id', models.CharField(max_length=50, unique=True)),
                ('boat_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('qr_code', models.CharField(max_length=200, unique=True)),
                ('qr_last_used', models.DateTimeField(blank=True, null=True)),
                ('last_latitude', models.FloatField(blank=True, null=True)),
                ('last_longitude', models.FloatField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('total_entries', models.IntegerField(default=0)),
                ('suspicious_activity_count', models.IntegerField(default=0)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('boat_image', models.ImageField(blank=True, null=True, upload_to='boats/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registered Boat',
                'verbose_name_plural': 'Registered Boats',
            },
        ),
        migrations.CreateModel(
            name='QRScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distance_from_last_scan', models.FloatField(blank=True, null=True)),
                ('time_since_last_scan', models.FloatField(blank=True, null=True)),
                ('calculated_speed', models.FloatField(blank=True, null=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicion_reason', models.TextField(blank=True, null=True)),
                ('capture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camera.boatcapture')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='camera.registeredboat')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
