# Generated by Django 5.2.8 on 2025-11-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoatCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='captures/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('qr_detected', models.BooleanField(default=False)),
                ('qr_data', models.TextField(blank=True, null=True)),
                ('qr_valid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'OK - No Threat'), ('warning', 'WARNING - Alert')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Boat Capture',
                'verbose_name_plural': 'Boat Captures',
                'ordering': ['-captured_at'],
            },
        ),
    ]
