# Generated by Django 5.2.8 on 2025-11-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_registeredboat_qrscanlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
