"""
Django settings for oceanguard project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Base Directory
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z&4_uof9j#x0efoe_w$+kvf-ex@m_&qmy@x85g7ni+q5&sgijp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Allow all devices on local WiFi


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'camera',   # ✅ Your App
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'oceanguard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # ✅ Add this line
                'django.template.context_processors.media',  # ✅ Add this line
            ],
        },
    },
]

WSGI_APPLICATION = 'oceanguard.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password Validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'   # ✅ India Time
USE_I18N = True
USE_TZ = True


# Static Files
STATIC_URL = 'static/'

# ✅ Media: Where camera images are stored
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================
# 🚢 OCEANGUARD CUSTOM SETTINGS
# ============================================

# QR Code Scanning
QR_SCAN_ENABLED = True

# ML Boat Detection Settings
ML_BOAT_DETECTION_ENABLED = True  # Enable/Disable ML boat detection
ML_CONFIDENCE_THRESHOLD = 0.5  # 50% confidence for boat detection
# Classes to detect as "boats" (COCO dataset labels)
BOAT_CLASSES = ['boat', 'ship', 'sailboat', 'speedboat', 'vessel']

# Camera GPS Location (Update with actual coordinates)
CAMERA_GPS_LOCATION = {
    'latitude': 19.0760,   # Mumbai Port example
    'longitude': 72.8777,
    'location_name': 'Port Entry Gate',
    'installation_height': 10,  # meters
}
